name: Build artifact

on:
  push:
    branches: 
      "main"

jobs:
  build:
    name: Build Pico Project
    runs-on: ubuntu-latest

    steps:
      - name: Checout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Pico Project
        id: build
        uses: samyarsadat/Pico-Build-Action@v1
        with:
          source_dir: "./"
          cmake_args: >
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_CXX_STANDARD=17
            -DCMAKE_CXX_STANDARD_REQUIRED=ON

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build artifact
          path: |
            ${{ steps.build.outputs.output_dir }}/**/*.uf2
